version: '3'

services:
  backend:
    build:
      context: ./backend/library_management
      dockerfile: Dockerfile
    ports:
      - "8282:8282"
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@db:1521/ORCLPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      CHOKIDAR_USEPOLLING: "true" 
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/library_management
      dockerfile: Dockerfile
    networks:
      - app-network

  db:
    image: oracle/database:19.3.0
    environment: 
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: 1234
    ports:
      - "1522:1521"
      - "5500:5500"
    volumes:
      - db_data:/opt/oracle/oradata
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - D:/java/Library_management_Project/certs/librarymanagement.duckdns.org:/etc/letsencrypt/live/librarymanagement.duckdns.org:ro
      - ./frontent/library_management/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - D:/java/Library_management_Project/certs/librarymanagement.duckdns.org:/etc/letsencrypt
      - ./certbot-etc:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'while :; do sleep 12h && certbot renew; done'"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
